dist: xenial

language: cpp

script: python waf configure --enable-vst3 --enable-ladspa --system-jpeg --projucer clean build

before_install:
  - sudo apt-get install -y libasound-dev libx11-dev libxext-dev libxinerama-dev libxrandr-dev libxcursor-dev libgtk+-3.0 libwebkit2gtk-4.0 libgl-dev ladspa-sdk libjpeg-dev

addons:
  apt:  
    update: true
